DEBUG = True
TIME_ZONE = 'UTC'

DB_NAME = ''
DB_USER = ''
DB_PASSWORD = ''

EMAIL_HOST = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = ''
EMAIL_USE_TLS = True
EMAIL_YOU = 'admin@geeksblog.com'
